dist: trusty
language: tex
sudo: false

addons:
    apt: 
        packages:
          - texlive-full
          - biber
script:
  - pdflatex -interaction=nonstopmode -halt-on-error *.tex
  - biber *.bcf
  - pdflatex -interaction=nonstopmode -halt-on-error *.tex
deploy:
  provider: releases
  api_key: $GIT_AUTH
  file: "PAWI_HS18_Projektdokumentation.pdf"
  skip_cleanup: true
  tags:
    true
