dist: trusty
language: tex
sudo: false

addons:
    apt: 
        packages:
          - texlive-full
script:
  - pdflatex -interaction=nonstopmode -halt-on-error *.tex
  - pdflatex -interaction=nonstopmode -halt-on-error *.tex
